/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import koneksi.connection;
import login.HalamanMenu;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import tampilan.About;
/**
 *
 * @author Ryan
 */
public class DataMitra extends javax.swing.JFrame {
        private Connection conn = new connection().clsconnect();
        private DefaultTableModel tabmode;
        
        protected void datatable(){
        Object[] Baris = {"ID Mitra","Nama Mitra", "Status Mitra", "Alamat", "No Hp"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelMitra.setModel(tabmode);
        String sql = "select * from dmitra";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_mitra");
                String b = hasil.getString("nama_mitra");
                String c = hasil.getString("alamat_mitra");
                String d = hasil.getString("no_hp");
                String e = hasil.getString("status_mitra");
                
                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            
        }
    }

    /**
     * Creates new form DataCustomer
     */
    public DataMitra() {
        this.setTitle("Data Mitra");
        initComponents();
        datatable();
        setLocationRelativeTo(getRootPane());
        setIconImage();
    }
    
    protected void aktif(){
        txtidm.setText("");
        txtNamalengkap.setEnabled(true);
        txtNamalengkap.setEnabled(true);
        txtStatus.setEnabled(true);
        txtAlamat.setEnabled(true);
        txtNoHp.setEnabled(true);
    }
    
    protected void bersih(){
        txtidm.setText("");
        txtNamalengkap.setText("");
        txtStatus.setText("");
        txtAlamat.setText("");
        txtNoHp.setText("");
        tCari.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamalengkap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtidm = new javax.swing.JTextField();
        bsave2 = new javax.swing.JButton();
        bhapus1 = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bclear1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bexit = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMitra = new javax.swing.JTable();
        tCari = new javax.swing.JTextField();
        bCari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        brefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 530));
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(51, 0, 102));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nomor Telepon");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));
        jPanel1.add(txtNamalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Mitra");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, -1));
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Lengkap");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status Mitra");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtNoHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoHpKeyTyped(evt);
            }
        });
        jPanel1.add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat Mitra");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));
        jPanel1.add(txtidm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, 30));

        bsave2.setBackground(new java.awt.Color(51, 0, 102));
        bsave2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bsave2.setForeground(new java.awt.Color(255, 255, 255));
        bsave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        bsave2.setText("SAVE");
        bsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsave2ActionPerformed(evt);
            }
        });
        jPanel1.add(bsave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 100, 30));

        bhapus1.setBackground(new java.awt.Color(51, 0, 102));
        bhapus1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bhapus1.setForeground(new java.awt.Color(255, 255, 255));
        bhapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        bhapus1.setText("DELETE");
        bhapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapus1ActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 100, 30));

        bedit.setBackground(new java.awt.Color(51, 0, 102));
        bedit.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        bedit.setForeground(new java.awt.Color(255, 255, 255));
        bedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.png"))); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 100, 30));

        bclear1.setBackground(new java.awt.Color(51, 0, 102));
        bclear1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bclear1.setForeground(new java.awt.Color(255, 255, 255));
        bclear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        bclear1.setText("CANCEL");
        bclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear1ActionPerformed(evt);
            }
        });
        jPanel1.add(bclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 100, 30));

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, 510));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Created By Ryanprawira");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA MITRA");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, 40));

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -10, 1000, 50));

        bexit.setBackground(new java.awt.Color(51, 0, 102));
        bexit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bexit.setForeground(new java.awt.Color(255, 255, 255));
        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        bexit.setText("EXIT");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        Background.add(bexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 100, 30));

        bprint.setBackground(new java.awt.Color(51, 0, 102));
        bprint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bprint.setForeground(new java.awt.Color(255, 255, 255));
        bprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printer.png"))); // NOI18N
        bprint.setText("PRINT");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });
        Background.add(bprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 100, 30));

        tabelMitra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Mitra", "Nama Mitra", "Status Mitra", "Alamat", "No Hp"
            }
        ));
        tabelMitra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMitraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMitra);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 710, 390));
        Background.add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 280, 30));

        bCari.setBackground(new java.awt.Color(255, 255, 255));
        bCari.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/searc.png"))); // NOI18N
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });
        Background.add(bCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pencarian");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATA MITRA");
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 170, -1));

        brefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        brefresh.setText("REFRESH");
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });
        Background.add(brefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, 30));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1010, 600));

        setSize(new java.awt.Dimension(1016, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        Object[] Baris = {"ID Mitra", "Nama Mitra", "Status Mitra", "Alamat", "No Hp"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelMitra.setModel(tabmode);
        String sql = "SELECT * FROM dmitra WHERE id_mitra like '%"+tCari.getText()+"%' OR nama_mitra like '%"+tCari.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_mitra");
                String b = hasil.getString("nama_mitra");
                String c = hasil.getString("alamat_mitra");
                String d = hasil.getString("no_hp");
                String e = hasil.getString("status_mitra");

                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bCariActionPerformed

    private void tabelMitraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMitraMouseClicked
        int bar = tabelMitra.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();

        txtidm.setText(a);
        txtNamalengkap.setText(b);
        txtStatus.setText(c);
        txtAlamat.setText(d);
        txtNoHp.setText(e);
    }//GEN-LAST:event_tabelMitraMouseClicked

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        HalamanMenu Menu = new HalamanMenu();
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    private void bclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear1ActionPerformed
        bersih();
        datatable();
    }//GEN-LAST:event_bclear1ActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed

        try {
            String sql = "update dmitra set nama_mitra=?, alamat_mitra=?, no_hp=?, status_mitra=? where id_mitra=?";

            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1, txtNamalengkap.getText());
            stat.setString(2, txtStatus.getText());
            stat.setString(3, txtAlamat.getText());
            stat.setString(4, txtNoHp.getText());
            stat.setString(5, txtidm.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            bersih();
            txtidm.requestFocus();
            datatable();

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapus1ActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Ingin menghapus data? ", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            String sql="delete from dmitra where id_mitra='"+txtidm.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                bersih();
                txtidm.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus "+e);
            }
        }
    }//GEN-LAST:event_bhapus1ActionPerformed

    private void bsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsave2ActionPerformed
        String sql = "insert into dmitra values (?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtidm.getText());
            stat.setString(2, txtNamalengkap.getText());
            stat.setString(3, txtStatus.getText());
            stat.setString(4, txtAlamat.getText());
            stat.setString(5, txtNoHp.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            bersih();
            txtidm.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_bsave2ActionPerformed

    private void txtNoHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoHpKeyTyped
        if (Character.isAlphabetic (evt.getKeyChar())){
            evt.consume();   JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        if ( txtNoHp.getText().length() == 15 ) {
            evt.consume();   JOptionPane.showMessageDialog(null, "Masukan Tidak Boleh Lebih Dari 15", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtNoHpKeyTyped

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        bersih();
        datatable();
    }//GEN-LAST:event_brefreshActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        JasperReport reports;
        
        String path = ".\\src\\Report\\LaporanMitra.jasper";
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(StokBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMitra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton bCari;
    private javax.swing.JButton bclear1;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bhapus1;
    private javax.swing.JButton bprint;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton bsave2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tabelMitra;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNamalengkap;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtidm;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/vapor-removebg-preview.png")).getImage());
    }
}
